apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.nameOverride }}
  namespace : {{ .Values.namespace }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: {{ .Values.nameOverride }}-{{ .Values.env }}